### ISSUE TITLE
Taxonomic classification in alien data class

### ISSUE THREAD

**Issue by david-beauchesne** [TheoreticalEcosystemEcology/alien#26]
Another list should be included in the data class to incorporate taxonomic classification of species. Ideally, here are the specification that we should use (as per our discussions yesterday)

- If user provides taxonomic classification, use it.
- If user to not provide taxonomic classification but provide phylogeny, extract taxonomic classification from phylogeny
- Taxonomic classification should be uniform between species (e.g. all include kingdom, order, family, genus and species), or at least make the user aware that only classification levels without missing entries will be considered for analyses (talking here for the machine learning approach)
- Taxonomic classification should not have missing entries at coarser levels than the finer level provided. For exemple, if the species are classified to the species level and one entry has a species but not a family, it will not be used. However, if the species are classified to the species level and an entry correspond to a genus (with all coarser levels described), it should be used. 
- Some species are not described for certain taxonomic levels (e.g. order). I do not know how these should be incorporated. Maybe some sort of dummy variable that is unique in the taxonomic list, but not a missing entry?

**Comment by KevCaz** [comment]
> If user provides taxonomic classification, use it.

If the method to be applied allows to use such information!

I am not sure the way the information should be added. Actually, the data the user have determine the methods he can applied. To me, having different S4 objects with some links among them (*i.e.* using [inheritance](https://en.wikipedia.org/wiki/Inheritance_(object-oriented_programming)) as in the sp package) would have been a adequate solution... That being said, we could find a simple way to assign methods based on the information included in the S3 object we currently use.

**Comment by SteveViss** [comment]
@KevCaz, we use S3 objects for the moment. S4 is always a more painful experience for users... I think.

> That being said, we could find a simple way to assign methods based on the information included in the S3 object we currently use.

This is what we have in mind. Each level of the list (output of the `as.alienData()` function) are by default set as NULL. Hence, this is easy to test which methods might applied based on the content of the `as.alienData()` output.

**Comment by SteveViss** [comment]
Taxonomic information is now available within the `alienData` object. See `nmTaxo` and `dfNodes`. You can test your similarity function by calling `data(plantsPol)` or `data(salix)`. If needed, I can probably add the `phylo`to `plantsPol` but that step might need further coding hours, because phylogenetic informations are not available at the species and genus level (according to @MoralesCastilla ). I'm closing this issue for the moment.
