### ISSUE TITLE
Contribution guidelines

### ISSUE THREAD

**Issue by tpoisot** [TheoreticalEcosystemEcology/alien#3]
Most R styleguides say that functions should be CamelCased verbs that describe what they do. Please refactor.

**Comment by KevCaz** [comment]
and I think it's a good practice! We will use it !

**Comment by KevCaz** [comment]
Steve will be in charge of the harmony of the package! 
We have to write the practices we want to use as clearly as possible in the README !

**Comment by KevCaz** [comment]
Thanks for the CONTRIBUTING file! I've just read [this post](https://www.rstudio.com/rviews/2016/12/02/writing-good-r-code-and-writing-well/) aboutR style guide I found useful (as it provides a couple of ressources on this topic). I hope it could be helpful to chose extra rules if ever needed.

**Comment by KevCaz** [comment]
Concerning the CONTRIBUTING file, I think using [formatR](https://cran.r-project.org/web/packages/formatR/) is a good solution for at least 2 current 'typos':

1. [formatR](https://cran.r-project.org/web/packages/formatR/) takes care of spaces (*e.g*when enumerating arguments),
2. It can also convert `=` to `<-` using  `arrow = getOption("formatR.arrow",TRUE)` as a argument of `tidy_source()` function (also called by`tidy_dir()`.

Point 2 will be added in the small R script `pkg2date.R` I use for local package updates. Also, I think this script should not be included when we release the package.

**Comment by SteveViss** [comment]
Contributing guidelines is in the `README.md` file.
