### ISSUE TITLE
alienData new features

### ISSUE THREAD

**Issue by SteveViss** [TheoreticalEcosystemEcology/alien#31]
# Coffee break enhancements

__List of new functions:__

- print.alienData (brief summary of alienData object)
- summary.alienData
- plot.alienData (basic)
- predict.alienData (based on methods)
- alienData$availableMeths (Methods) is a new attribute

__Data format:__

- `data`: User provides data with a least the species ID column. 
   - Contains phylo and traits

- `Interact:` (data.frame or matrix) = edgeList
   - Guess IDs used in edge list based on data (IDs have to unique among species and ind)
   - If all(IDs is individus), by default FUN = sum, FUN argument available to let user defines is own function.

- `sites`: (data.frame or matrix)
   - Site ID: have to be unique by his own (not ID from species and individus)
    - One column by descriptors

- `siteSpecies`: (data.frame)

```r
as.alienData(
data, 
vecPosTrait = NULL,  # Traits
vecPosPhylo=vecPos or phyloObject,
interact,
sites,
vecPosLocation
vecPosAbioticVar
siteSpecies
)
```

1. Descriptors
- Individus or species but both level cannot coexist.
- Level set is defined based on column names.

**Comment by KevCaz** [comment]
I've taken care of many comments described in this issue on my branch `chgformat`. I still need to improve the doc and some testings remain to be implemented. I should be able to do date tomorow.

**Comment by KevCaz** [comment]
We do not need to deal with both indiviual and species information at the same time.

I think we shoud let the user chose the unit he wants to deal with and only check if it is consistent throughout the code. The nature of the nodes does not matter: the user could use genus / species / population / indivuduals / whatever, it's not the purpose of `as.alienData()` to check if this choice is relevant. What we need is checking whether the user uses consistent primary keys in the dataframes it passes to `as.alienData`.

Doing this should clarify the code (decrease its length / diminish the number of tests). What we should do is a function to allow the users to group interactions. Let's say the user has data on individuals, he should be able to groupe then by species (or whatever he wants).

I'm going to implement that on my branch!

**Comment by KevCaz** [comment]
As expected the code length decreased significantly (242 -> 198 lines). 

The code is clearer and way easier to test (I'll review the tests tomorow). I think it's good practice to have function of reasonable size when possible. In this case, it makes sense to me: 1- we simplify the function 2- we are not losing anything  (we offer new possibilities actually) as long as we code the function that allows the user to 'groupby' interactions to perform further analyses (i.e. from idividuals to species analyses).

**Comment by KevCaz** [comment]
I think the function `as.alienData()` should be `named` alienData to avoid confusion between function and methods especially given we use S3 methods. I'll do that on my branch and then start to implement `summary.alienData`.

**Comment by guiblanchet** [comment]
Actually, my original idea when I thought of defining <as.alienData> is for it to be a method of the function <as>.

**Comment by guiblanchet** [comment]
Oups..., weird it did not write properly... here goes again 

Actually, my original idea when I thought of defining `as.alienData` is for it to be a method of the function `as` .

**Comment by KevCaz** [comment]
IMHO,  an `as.alienData()` should allow the user to convert various formats into an alienData object as all the `as.xxxx()` functions do. For instance, `as.character()` is  a generic and there are:                  
- as.character.Date
- as.character.POSIXt
- as.character.condition
- as.character.default
- ... etc
to convert one specific format to an object of type *character*. 

Such functions could/should be written and they will actually use `alienData()` (I definitively see the interest of having a function such `as.alienData.igraph()`). I would say that `alienData()` is equivalent to the `data.frame()` function and we could/should implement a set of usefull `as.alienData.xxxx()` functions (equivalent to the `as.data.frame.xxxx()` functions). In that case, `as.alienData()` would be a generic function and we should have one `as.alienData.xxxx()` function for each format we target.

**Comment by guiblanchet** [comment]
OK! I see your point ! You have me on your side with the `alienData` function.

**Comment by KevCaz** [comment]
Thks :)
👍

**Comment by SteveViss** [comment]
Ok, thanks to @KevCaz. `alienData` object is final and is way much suitable for the next steps. Enhancements have been done under the #33 pull request.
