### ISSUE TITLE
alienData - siteEnv param

### ISSUE THREAD

**Issue by SteveViss** [TheoreticalEcosystemEcology/alien#36]
The `siteEnv` param is not taken in account in the `alienData` function.

**Comment by KevCaz** [comment]
right. I'll fix that asap.

**Comment by KevCaz** [comment]
So, I did not use `siteEnv`. All columns of dfSites are currently considered as sites' variables. 

Two options then:
 
1. we drop `siteEnv` (1 less parameter, not a bad idea)
2. I add few lines of code to take `siteEnv` into account

@SteveViss what do you think?

**Comment by SteveViss** [comment]
I'll go with the option 2. Declaring a `siteEnv` is an explicit and convenient way of saying to the user you can add environmental variable to your alienData object.

**Comment by SteveViss** [comment]
Actually, I add environmental variables to the `dfSites`in the `plantsPol` dataset but they don't show up in the alienData output.. weird..

**Comment by KevCaz** [comment]
I'll take care of implementing option 2, should fix the issues. I'll adequate tests too.

**Comment by SteveViss** [comment]
You should keep it open and assign any pushes related to this issue.

**Comment by KevCaz** [comment]
Well ok, but this specific issue is fixed (siteEnv is taken into account and tests check that the desired feature works)... If there are new pushes, they may solve different issues or add new features... 

That being said, let's keep this issue open as for now until your next sudden urge for closing as many issues as possible !!! 😸  😈

**Comment by SteveViss** [comment]
Sorry, my bad.. I haven't saw your push ;)

**Comment by KevCaz** [comment]
No worries! As maintainer, you are in charge of this kind of decision anyway. 
So thanks for taking care of this, and thanks for closing the issue. 👍
