### ISSUE TITLE
openmp problem

### ISSUE THREAD

**Issue by guiblanchet** [TheoreticalEcosystemEcology/alien#39]
Under Mac OS X, when I try to compile alien, I get the following error :

clang: error: unsupported option '-fopenmp'

which is related to some compiler issues. I am quite sure this error will occur again for different Macs. After taking a deeper look at the code, it is not exactly clear to me why this error occurs, @KevCaz any clue why this error occurs ?

**Comment by KevCaz** [comment]
I am pretty sure that I am guilty. I have a use Makevars file that is no longer required (I cannot remember why I did this, well I have to admit that there was a time where I foolishly do this type of thing without taking note :smiling_imp: ). 

So basically, we can get rid of `src/Makevars` and this should solve the issue. I'll have a careful look to add what version of  RcppArmadillo is required, and if we encounter weird compilation issues, I'll think about it again, but recent versions of Rcpp and RcppArmadilllo do a fantastic job.

**Comment by guiblanchet** [comment]
OK ! I just removed  `src/Makeover` and it compiled well on Mac OS X High Sierra (10.13) and Mojave (10.14).
