### ISSUE TITLE
Compiled code under Windows

### ISSUE THREAD

**Issue by guiblanchet** [TheoreticalEcosystemEcology/alien#44]
Under Windows, the C++ code does not compile properly and sends errors.

@KevCaz Since your are much more familiar with this code, I will let you fix this part of the code. That being said, if you need help do not hesitate to ask.

For now I moved all the C++ code and the related function on a branch called webFromNicheModel

**Comment by KevCaz** [comment]
Are you working on the master branch? Because, right now the error is: 

```
Error: (converted from warning) package 'HMSC' is not available (for R version 3.5.1 Patched)
```

**Comment by KevCaz** [comment]
Ok, just add it in the remote and import fields in the DESCRIPTION file.

**Comment by SteveViss** [comment]
The changes has to be done on the `webFromNicheModel` branch. I'm still compilation issue with Travis and appVeyor with Rcpp .

**Comment by SteveViss** [comment]
One librairie is missing. Travis reported: 
```
Error: package or namespace load failed for ‘alien’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/tmp/Rtmp6osmH5/Rinst3c6c3aa8f2c7/alien/libs/alien.so':
  /tmp/Rtmp6osmH5/Rinst3c6c3aa8f2c7/alien/libs/alien.so: undefined symbol: dgesdd_
```

**Comment by KevCaz** [comment]
So basically src has been removed from the master branch? and from webFromNicheModel?

**Comment by SteveViss** [comment]
Yes, for the moment. I'm still doing some tests on webFromNicheModel branch.

**Comment by KevCaz** [comment]
```
> test_check("alien")
  Loading required package: alien
  ── 1. Failure: check overfit (@test-fitMC.R#11)  ───────────────────────────────
  `fitMC(ald1, d = 5, 10, verbose = FALSE)` threw an error with unexpected message.
  Expected match: "npar < prod(dim(netObs)) is not TRUE"
  Actual message: "could not find function \"fitMC\""
```

name has been changed for `fitIMC()`

**Comment by SteveViss** [comment]
Yes, done !
